# Generated by Django 4.1.2 on 2023-01-21 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_id', models.URLField()),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catagory', models.ManyToManyField(to='api.catagory')),
            ],
        ),
        migrations.CreateModel(
            name='productinventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.PositiveIntegerField(default=0)),
                ('upc', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('store_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_digital', models.BooleanField(default=False)),
                ('weight', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_checked', models.DateTimeField(auto_now_add=True)),
                ('units', models.CharField(max_length=100)),
                ('units_sold', models.BigIntegerField()),
                ('productinventory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.productinventory')),
            ],
        ),
        migrations.CreateModel(
            name='media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.ImageField(upload_to='images/')),
                ('alt_text', models.TextField()),
                ('is_feature', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('productinventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productinventory')),
            ],
        ),
    ]
